import {
  faCloud,
  faMoon,
  faCloudRain,
  faSnowflake,
  faThunderstorm,
  faCloudSun,
  faSun,
  faWind,
  faCloudSunRain,
  faIcicles,
  faTemperatureArrowUp,
  faTemperatureArrowDown,
  faCloudMoon,
  faCloudMoonRain,
} from '@fortawesome/free-solid-svg-icons';

enum IconKey {
  Sunny = 1,
  MostlySunny = 2,
  PartlySunny = 3,
  IntermittentClouds = 4,
  HazySunshine = 5,
  MostlyCloudy = 6,
  Cloudy = 7,
  Dreary = 8,
  Fog = 11,
  Showers = 12,
  MostlyCloudyWithShowers = 13,
  PartlySunnyWithShowers = 14,
  ThunderStorms = 15,
  MostlyCloudyWithThunderStorms = 16,
  MostlySunnyWithThunderStorms = 17,
  Rain = 18,
  Flurries = 19,
  MostlyCloudyWithFlurries = 20,
  PartlySunnyWithFlurries = 21,
  Snow = 22,
  MostlyCloudyWithSnow = 23,
  Ice = 24,
  Sleet = 25,
  FreezingRain = 26,
  RainAndSnow = 29,
  Hot = 30,
  Cold = 31,
  Windy = 32,
  Clear = 33,
  MostlyClear = 34,
  PartlyCloudy = 35,
  IntermittentCloudsNight = 36,
  HazyMoonlight = 37,
  MostlyCloudyNight = 38,
  PartlyCloudyWithShowers = 39,
  MostlyCloudyWithShowersNight = 40,
  PartlyCloudyWithThunderStorms = 41,
  MostlyCloudyWithThunderStormsNight = 42,
  MostlyCloudyWithFlurriesNight = 43,
  MostlyCloudyWithSnowNight = 44,
}

const iconMap = {
  [IconKey.Sunny]: faSun,
  [IconKey.MostlySunny]: faCloudSun,
  [IconKey.PartlySunny]: faCloudSun,
  [IconKey.IntermittentClouds]: faCloudSun,
  [IconKey.HazySunshine]: faCloudSun,
  [IconKey.MostlyCloudy]: faCloud,
  [IconKey.Cloudy]: faCloud,
  [IconKey.Dreary]: faCloud,
  [IconKey.Fog]: faCloud,
  [IconKey.Showers]: faCloudRain,
  [IconKey.MostlyCloudyWithShowers]: faCloudRain,
  [IconKey.PartlySunnyWithShowers]: faCloudSunRain,
  [IconKey.ThunderStorms]: faThunderstorm,
  [IconKey.MostlyCloudyWithThunderStorms]: faThunderstorm,
  [IconKey.MostlySunnyWithThunderStorms]: faThunderstorm,
  [IconKey.Rain]: faCloudRain,
  [IconKey.Flurries]: faSnowflake,
  [IconKey.MostlyCloudyWithFlurries]: faSnowflake,
  [IconKey.PartlySunnyWithFlurries]: faSnowflake,
  [IconKey.Snow]: faSnowflake,
  [IconKey.MostlyCloudyWithSnow]: faSnowflake,
  [IconKey.Ice]: faIcicles,
  [IconKey.Sleet]: faIcicles,
  [IconKey.FreezingRain]: faSnowflake,
  [IconKey.RainAndSnow]: faSnowflake,
  [IconKey.Hot]: faTemperatureArrowUp,
  [IconKey.Cold]: faTemperatureArrowDown,
  [IconKey.Windy]: faWind,
  [IconKey.Clear]: faMoon,
  [IconKey.MostlyClear]: faMoon,
  [IconKey.PartlyCloudy]: faCloud,
  [IconKey.IntermittentCloudsNight]: faCloudMoon,
  [IconKey.HazyMoonlight]: faCloudMoon,
  [IconKey.MostlyCloudyNight]: faCloudMoon,
  [IconKey.PartlyCloudyWithShowers]: faCloudRain,
  [IconKey.MostlyCloudyWithShowersNight]: faCloudMoonRain,
  [IconKey.PartlyCloudyWithThunderStorms]: faCloudRain,
  [IconKey.MostlyCloudyWithThunderStormsNight]: faCloudMoonRain,
  [IconKey.MostlyCloudyWithFlurriesNight]: faSnowflake,
  [IconKey.MostlyCloudyWithSnowNight]: faSnowflake,
};

export default iconMap;
